version: '3'
services:
  dev:
    image: ruby
    command: bash
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - GEM_HOME=/code/.bundle
      - BUNDLE_PATH=/code/.bundle
      - PATH=/code/.bundle/bin:$PATH
  db:
    image: postgres
    volumes:
      - ./todos-db:/var/lib/postgresql/data
  # api:
  #   image: ruby
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   working_dir: /code
  #   volumes:
  #     - .:/code
  #   environment:
  #     - GEM_HOME=/code/.bundle
  #     - BUNDLE_PATH=/code/.bundle
  #     - PATH=/code/.bundle/bin:$PATH
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db